name: Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Check for lock files and install dependencies
        run: |
          if [ -f "package-lock.json" ]; then
            echo "Found package-lock.json, using npm ci"
            npm ci
          elif [ -f "yarn.lock" ]; then
            echo "Found yarn.lock, using yarn install"
            yarn install --frozen-lockfile
          else
            echo "No lock file found, using npm install"
            npm install
          fi

      - name: Update dependencies
        run: |
          # Update all dependencies to latest versions
          npx npm-check-updates -u
          
          # Install updated dependencies
          if [ -f "yarn.lock" ]; then
            echo "Using yarn to install updated dependencies"
            yarn install
          else
            echo "Using npm to install updated dependencies"
            npm install
          fi

      - name: Run tests
        run: |
          if [ -f "yarn.lock" ]; then
            yarn test
          else
            npm test
          fi
        continue-on-error: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update npm dependencies'
          title: 'chore: update npm dependencies'
          body: |
            This PR updates npm dependencies to their latest versions.
            
            Please review the changes and ensure all tests pass before merging.
          branch: dependency-updates
          delete-branch: true
